name: Build WebGL

on:
  push:
    branches: 
      - main
      - feature/64
  pull_request:
    branches:
      - main

jobs:
  buildWebGL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.34f1
          targetPlatform: WebGL
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL
          
      - name: Push to another repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # clone target repo
          git clone https://x-access-token:${{ secrets.WORD_ONLINE_PLAY_TOKEN }}@github.com/Apptive-Game-Team/WordOnline_Play.git

          cd WordOnline_Play

          # copy build result
          rm -rf ./build
          rm -rf ./index.html
          cp -r ../build/WebGL/* ./

          git add .
          git commit -m "Update WebGL build from main repo"
          git push origin main